version: "3.9"

services:
  recipe-assistant:
    build: .
    container_name: recipe-assistant
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - QDRANT_URL=http://qdrant:6333  # Override for Docker
    volumes:
      - .:/app   # mount local code for dev
    depends_on:
      qdrant: # make sure qdrant is started before the app
        condition: service_healthy  # Wait for healthy status
    command: uv run uvicorn recipe_assistant.app.main:app --reload --host 0.0.0.0 --port 8000
    restart: unless-stopped

  qdrant:
    build:
      context: .
      dockerfile: Dockerfile.qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readyz"]
      interval: 15s
      timeout: 10s
    restart: unless-stopped
