###
GET http://localhost:8000/

###
POST http://localhost:8000/api/v1/question
content-type: application/json

{
    "question": "Can you give me a beef recipe, and show me the ingredients and the steps?",
    "llm_model": "gpt-4o-mini"
}

###
POST http://localhost:8000/api/v1/feedback
content-type: application/json

{
    "conversation_id": "00f8566f-db3e-4505-8625-949637521b06",
    "feedback": 1
}

###
POST http://localhost:8000/api/v1/question
content-type: application/json

{
    "question": "Can you give me a chicken recipe?",
    "llm_model": "gpt-4o-mini"
}

###
POST http://localhost:8000/api/v1/feedback
content-type: application/json

{
    "conversation_id": "1ce0521f-9ae4-4777-8a23-621cac3c7e72",
    "feedback": 1
}

###
POST http://localhost:8000/api/v1/question
content-type: application/json

{
    "question": "What are the ingredients of Lasagna?",
    "llm_model": "gpt-4o-mini"
}

###
POST http://localhost:8000/api/v1/feedback
content-type: application/json

{
    "conversation_id": "00978df2-59ed-4ca4-bd26-73b74f09f142",
    "feedback": 1
}

###
POST http://localhost:8000/api/v1/question
content-type: application/json

{
    "question": "Can you give me a salad recipe?",
    "llm_model": "gpt-4o-mini"
}

###
POST http://localhost:8000/api/v1/feedback
content-type: application/json

{
    "conversation_id": "b2f10de6-5a47-46de-b6b5-951186b5700c",
    "feedback": 1
}

###
POST http://localhost:8000/api/v1/question
content-type: application/json

{
    "question": "Can you give me a recipe of a Japanses dish?",
    "llm_model": "gpt-4o-mini"
}

###
POST http://localhost:8000/api/v1/feedback
content-type: application/json

{
    "conversation_id": "646bb05e-04dc-4aac-8f11-10987165ecf6",
    "feedback": 1
}